---
# This playbook will httpd

#- name: Install Yum utils
#  yum: name={{ item }} state=present
#  with_items:
#  - epel-release
#   - yum-utils

#- name: Install remi.
#  apt:
#    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
#    state: present
#
#- name: Enable EPEL repo
#  command: yum-config-manager --enable remi-php73
#  become: yes
  
- name: Install httpd and php
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php
   - php-mysql
   - libapache2-mod-php
   - php-bcmath
   - php-curl
   - php-imagick
   - php-intl
   - php-json
   - php-mbstring
   - php-xml
   - php-zip
   - firewalld
   - mysql-client-core-8.0

#- name: Stop firewalld
#  service: name=firewalld state=stopped enabled=no
- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  service: name=apache2 state=started enabled=yes

#- name: Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
